version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: bookrooms-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=bookrooms_development
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:

networks:
  default:
    ipam:
      config:
        - subnet: 10.18.0.0/16
          gateway: 10.18.0.1
